env                         = "dev"
project_code                = "IncrediblESGProcessor"
deployment_package_location = "../build"
custom_domain_name          = "incrediblesgprocessor.algebananazzzzz.com"
regional_certificate_domain = "*.algebananazzzzz.com"
route53_zone_name           = "algebananazzzzz.com"
